name: Build and Push

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'

jobs:
  run-migrations-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Database Migrations
        id: migrations
        run: |
          sh .github/workflows/import-secrets-to-process-env.sh dev-env-file
          yarn migrate

  run-migrations-qa:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Database Migrations
        id: migrations
        run: |
          sh .github/workflows/import-secrets-to-process-env.sh qa-env-file
          yarn migrate

  build-and-deploy-dev:
    runs-on: ubuntu-latest
    needs: run-migrations-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Deploy to Dev
        run: yarn deploy:dev

      - name: Set secrets for Dev
        run: |
          sh .github/workflows/secrets.sh dev-env-file
          sh .github/workflows/list-lambda-functions.sh dev us-west-1
          while IFS= read -r lambda_name; do
            echo "Updating environment for $lambda_name"
            aws lambda update-function-configuration --function-name "$lambda_name" --environment file://secrets.json > /dev/null 2>&1
          done < lambda-names
          rm lambda-names
          rm secrets.json

  build-and-deploy-qa:
    runs-on: ubuntu-latest
    needs: run-migrations-qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Deploy to QA
        run: yarn deploy:qa

      - name: Set secrets for QA
        run: |
          sh .github/workflows/secrets.sh qa-env-file
          echo $(npx sls info --verbose)
          sh .github/workflows/list-lambda-functions.sh qa us-east-1
          while IFS= read -r lambda_name; do
            echo "Updating environment for $lambda_name"
            aws lambda update-function-configuration --function-name "$lambda_name" --environment file://secrets.json > /dev/null 2>&1
          done < lambda-names
          rm lambda-names
          rm secrets.json